### ISSUE TITLE
objc2 vs thin wrappers as solutions for framework interface

### ISSUE THREAD

**Issue by josephjohnston** [madsmtm/objc2#294]
This question may hardly make sense (as I hardly understand ffi), but I hope you can explain.
Suppose you want to interface with an objective-C framework from another language.
Two examples below show different solutions, and of course objc2 serves as a solution for rust.
I'm trying to understand the reasoning behind these different solution (examples 1 and 2, and objc2).
I'm hoping you can comment on the difference between them, and the pros and cons of each.

1. [An interface](https://github.com/recp/cmt) for the Metal framework from C to objective-C. 
The approach I see here is to make simple conversion for primitive types, and represent most objects as `void *`, provide a C interface using these types, and have the implementation of the interface in objective-c casting these types into objective-c equivalents and calling the relevant objective-c functions. 
3. [An interface](https://github.com/dcuddeback/core-foundation-sys) for the core-foundation framework from rust to objective-C. 
The approach I see here uses similar types through libc, but doesn't provide any objective-C implementations like the previous example because core-foundation is in C rather than  objective-C (so I guess this example is less relevant).

It seems that objc2 is much more powerful in general by offering access to the runtime, allowing creation and manipulation of classes and instances, whereas the examples just provide thin wrappers over frameworks.
So of course objc2 and these thin wrappers are very different.
But if one's purpose is just to interface with a framework, do all the features of objc2 offer much over these simple wrapper solutions?
If so, why is objc2 a better choice and why may one not want to use thin wrapper approaches like the examples?
If not, then why do projects like [metal-rs](https://github.com/gfx-rs/metal-rs) go through objc rather than take a simpler approach like the examples above?

**Comment by madsmtm** [comment]
I think the main thing to realize is that **calling Objective-C code from Rust _requires_ extra glue code compared to calling C code**. The Rust compiler makes it easy to do your example 2 with `extern "C"`, but no such thing as `extern "Objective-C"` exist, so `objc2` (or `objc`) must fill that gap.

In your example 1, they can do it since the code is compiled using `clang`, which natively supports Objective-C. Other languages like Swift (and somewhat Nim and D) also have built-in support, so they wouldn't need a library like `objc2`.

Another thing to note is that to use many Objective-C APIs (for example `NSView`, `NSWindowDelegate`, ...), you need to create a subclass - so if we want to make full use of these, we have to be able to create classes from Rust as well.

Hope that helped, feel free to ask me to clarify something!

**Comment by josephjohnston** [comment]
I see, all those points make sense.
Example 2 isn't relevant. As for example 1, I'm still confused, why wouldn't it work to compile (eg with `clang`) the objective-C written wrapper library, which exposes a C interface, and then link that against rust?
So the objective-C to C glue is written in objective-C (as in example 1), using I think core-foundation's `__bridge` and `CFBridgingRetain` and `CFBridgingRelease` (for some reason example 1 doesn't use them), and then I assume a compiled library with a C interface can be easily glued to rust.
Where might this be troublesome?

**Comment by madsmtm** [comment]
> As for example 1, I'm still confused, why wouldn't it work to compile (eg with `clang`) the objective-C written wrapper library, which exposes a C interface, and then link rust against that? So the objective-C to C glue is written in objective-C (as in example 1), using I think core-foundation's `__bridge` and `CFBridgingRetain` and `CFBridgingRelease` (for some reason example 1 doesn't use them), and then I assume a compiled library with a C interface can be easily glued to rust. Where might this be troublesome? (I've been trying this today but run into problems for other reasons since I'm new to all this)

Oh sorry, didn't understand you properly before. You can definitely do that, e.g. using a `build.rs` script and the `cc` crate - see also `objc-sys` which may be able to do some of this for you.

To compare the two approaches, let's say we wanted to map `+[NSData dataWithBytes:length:]` to be called as `NSData::with_bytes` in Rust, we would need to do:

- Approach A, using `objc2` (going Rust -> Objective-C)
    ```rust
    // NSData.rs
    use objc2::...;

    type NSData = ...;

    impl NSData {
        // Direct binding to the method
        unsafe fn with_bytes_inner(bytes: *const c_void, length: NSUInteger) -> Id<Self, Shared> {
            unsafe { msg_send_id![Self::class(), dataWithBytes: bytes, length: length] }
        }

        // "Rusty", manually written API
        pub fn with_bytes(bytes: &[u8]) -> Id<Self, Shared> {
            unsafe { with_bytes_inner(bytes.as_ptr().cast(), bytes.len()) }
        }
    }
    ```
- Approach B, using `clang` (going Rust -> C -> Objective-C)
    ```objective-c
    // NSData.m
    #import <Foundation/NSData.h>

    NSData* NSData_with_bytes(void* bytes, NSUInteger length) {
        return [NSData dataWithBytes: bytes length: length];
    }
    ```

    ```rust
    // NSData.rs
    use objc2::...;
    
    type NSData = ...;

    extern "C" {
        fn NSData_with_bytes(bytes: *const c_void, length: NSUInteger) -> *const NSData;
    }

    impl NSData {
        // "Rusty", manually written API
        pub fn with_bytes(bytes: &[u8]) -> Id<Self, Shared> {
            let data = unsafe { NSData_with_bytes(bytes.as_ptr().cast(), bytes.len()) };
            into_id_with_proper_memory_management(data) // Details omitted for brevity
        }
    }
    ```

I personally like approach A the most, primarily because I think it's a lot less work; you only have to keep your eyes on one file at a time. Another plus to this approach is that it is also more efficient, since you don't incur the overhead of an extra function call.

A plus to approach B though is that you would be 100% sure that the ABI/calling convention was correctly implemented (I'm pretty sure that is the case for `objc2` as well, but there may be a bug hidden somewhere).

There's a lot more nuance to this of course, but I hope that gave you a bit more understanding of the issue.

**Comment by josephjohnston** [comment]
Your two sketches are illuminating for me.
What I had in mind was trying without objc2, something like below. 
I'm sure it's wrong is several ways, especially the typing (though it doesn't crash), but I hope you get the drift.
You're right about the inconvenience of two files, and I now realize even the example 1 C implementation I gave above has the overhead of an extra function call.
While I find the simplicity beneficial (without a sophisticated intermediary like objc2), I don't find it worth the two downsides you mentioned, not to mention its own safety concerns.
```objective-c
// NSData.m
#import <Foundation/Foundation.h>

CFDataRef NSData_with_bytes(void* bytes, NSUInteger length) {
    NSData *data = [NSData dataWithBytes: bytes length: length];
    return CFBridgingRetain(data);
}
void NSData_print_description(CFDataRef dataRef) {
    NSData *data = (__bridge NSData*)dataRef;
    NSLog(@"%@", [data description]);
}
void NSData_release(CFDataRef dataRef) {
    NSData *data = (NSData *)CFBridgingRelease(dataRef);
}
```
```rust
// NSData.rs
struct NSData(*const libc::c_void);
type NSUInteger = usize;

extern "C" {
    fn NSData_with_bytes(bytes: *const libc::c_void, length: NSUInteger) -> NSData;
    fn NSData_print_description(data: NSData);
    fn NSData_release(data: NSData);
}

impl NSData {
    pub fn with_bytes(bytes: &[u8], length: NSUInteger) -> NSData {
        unsafe { NSData_with_bytes(bytes.as_ptr().cast(), length) }
    }
    pub fn print_description(&self) {
        unsafe { NSData_print_description(NSData(self.0)) };
    }
    fn release(&self) {
        unsafe { NSData_release(NSData(self.0)) };
    }
}
impl Drop for NSData {
    fn drop(&mut self) {
        self.release();
    }
}

fn main() {
    let bytes: &[u8] = &[0, 1, 2, 3, 4, 5, 6, 7];
    let data = NSData::with_bytes(bytes, 8);
    data.print_description();
    // prints: {length = 8, bytes = 0x0001020304050607}
}
```
