### ISSUE TITLE
How to use Id for typical no-retain/release case

### ISSUE THREAD

**Issue by josephjohnston** [madsmtm/objc2#299]
Objective-C memory management policy says that one may call a method and assume a returned object remains valid for the time needed, with the two exceptions that the object is removed from a fundamental collection type, or that the parent object may be deallocated during the time one needs the child object.

As such, whenever calling a method to receive an object, if the returned object is not newly created, then typically (with the said two exceptions) you can work with the returned object without retaining or releasing it. The returned object may well have type id.
But in objc2 the analogous type Id only seems applicable when the returned object is newly created (using `new`), or when you must retain the returned object for one of the said exceptions (using `retain` or `retain_autoreleased`). How, then, to accommodate the typical case of receiving a returned object of type id, representing it with type Id, and yet never retaining or releasing it?
Or what do I misunderstand?

**Comment by josephjohnston** [comment]
make the call with `msg_send_id!` and the return type can be `Id<_, _>`

**Comment by madsmtm** [comment]
Indeed, `msg_send_id!` handles the details of when to use `Id::retain_autoreleased` for you, just like ARC does, glad you figured it out ;)

Note that it is certainly _possible_ to not retain the object an extra time, however it is usually both more efficient (since otherwise the object will have to be sent to the current autorelease pool, which is expensive) and more ergonomic to do it.
