### ISSUE TITLE
Can't have `NSString` and `NSNumber` as values in an `NSDictionary`

### ISSUE THREAD

**Issue by mwcampbell** [madsmtm/objc2#306]
I don't see a way to create an `NSDictionary` with an `NSString` and an `NSNumber` as values, because the public Rust API for `NSDictionary` requires values to be `Owned` references, and this isn't possible for `NSString` and `NSNumber`. This blocks me from posting announcement notifications in the AccessKit macOS adapter, unless I use an unsafe workaround.

**Comment by madsmtm** [comment]
Indeed, this is an issue.

In #264 I'm experimenting with adding ownership parameters to `NSDictionary` as well (so `NSDictionary<Key, Value, KeyOwnership, ValueOwnership>`, which should solve this.

**Comment by madsmtm** [comment]
This is partially fixed now, since [`NSMutableDictionary::setObject_forKey`](https://docs.rs/icrate/0.0.1/icrate/Foundation/struct.NSMutableDictionary.html#method.setObject_forKey) is now available regardless of the dictionary's key and value ownership.

Though I haven't updated the helper implementations, so e.g. `NSMutableDictionary::insert` is currently unsound.
