### ISSUE TITLE
[icrate] Missing CoreGraphics and functions required for HDR/EDR

### ISSUE THREAD

**Issue by mbrla0** [madsmtm/objc2#485]
Is there any reason why `icrate` is missing support for CoreGraphics? Additionally, I find it weird that this crate is also missing both the `setColorSpace` and `setWantsExtendedDynamicRangeContent` functions. These are needed to properly make use of one of the HDR modes (Extended Dynamic Range) supported by Metal, as explained in [this example](https://developer.apple.com/documentation/metal/hdr_content/performing_your_own_tone_mapping?language=objc).

(Edit: The functions are for properties in both `CAMetalLayer` and `MTKView`, my bad :))

**Comment by silvanshade** [comment]
> Is there any reason why `icrate` is missing support for CoreGraphics?

I crate doesn't have bindings for several of the `Core*` frameworks at this point, not just `CoreGraphics`.

The main reason why is because the custom [header-translator](https://github.com/madsmtm/objc2/tree/master/crates/header-translator) program that `icrate` uses to scan the frameworks and generate the Rust FFI declarations doesn't have great support for some of the lower-level more C-oriented functionality that the `Core*` frameworks require versus the more Objective-C oriented ones.

And although the `header-translator` generally works reasonably well, there are often times where certain methods have to be skipped during generation due to the `header-translator` not being able to correctly parse the corresponding code in the header, or support lacking for some part of the definition on the Rust side.

This is the case for [`setColorSpace`](https://github.com/madsmtm/objc2/blob/3d9b6864af05592fc18b1ab27b3da9ed3896bc53/crates/header-translator/translation-config.toml#L1130C1-L1130C14). And [`setWantsExtendedDynamicRangeContent`] isn't available because [`CAMetalLayer`] isn't supported by `icrate` yet (for the above reasons).

It's often still possible to work around these missing functions by using `msg_send_id!` to call the selector directly, although this is obviously less safe, so more care needs to be taken to ensure the types are correct.

**Comment by madsmtm** [comment]
`CAMetalLayer` is available since 05f678701d7a169105ae73d9955eb8077783b4d1, and in 888ba8168336ff6d8a3acffb0104c37343f9da58 I added a bit of documentation for how to interoperate with `core-graphics`.

Adding `CoreGraphics` proper is tracked in https://github.com/madsmtm/objc2/issues/556, so going to close this.

**Comment by madsmtm** [comment]
Update: CoreGraphics has been added in eaf268dc5010e17cfecc26257417bcab0943ab38, to be released [soon](https://github.com/madsmtm/objc2/milestone/6).
