### ISSUE TITLE
Using AtomicPtr as ivar

### ISSUE THREAD

**Issue by ilmai** [madsmtm/objc2#511]
It looks to me like the constraint for using AtomicPtrs in ivars is wrong, or alternatively I'm misunderstanding something.

The equivalent of `*mut c_void` is `AtomicPtr<c_void>` but `Encode` is only implemented for `AtomicPtr<T: RefEncode>`, and `c_void` isn't `RefCode`. I think the correct constraint should be `*mut T: RefEncode`?

**Comment by madsmtm** [comment]
The implementation on `AtomicPtr` is correct, the issue is that we're being a bit hacky around `c_void`, see https://github.com/madsmtm/objc2/blob/812a615bcd8647020016452565dcb3ab3c4d56a7/crates/objc2/src/encode.rs#L570-L572

Honestly, I should probably remove that hack, it's not really worth the inconsistency, and people who do FFI know not to use `&c_void` and `&mut c_void`.

In the meantime, you can use a wrapper like this:
```rust
#[repr(transparent)]
struct MyWrapper(AtomicPtr<c_void>);

unsafe impl Encode for MyWrapper {
    const ENCODING: Encoding = Encoding::Atomic(&Encoding::Pointer(&Encoding::Void));
}
```
