### ISSUE TITLE
Instructions for adding a Framework?

### ISSUE THREAD

**Issue by dongcarl** [madsmtm/objc2#544]
Wondering if there are instructions for how best to add a Framework? (E.g. which files to modify and which will be generated)

CONTRIBUTING.md seems to only cover git submodules.

Looking to add the SMAppService parts of ServiceManagement

**Comment by madsmtm** [comment]
The easiest instruction for me to give would be to look at [other PRs adding frameworks](https://github.com/madsmtm/objc2/pulls?q=is%3Apr+is%3Aclosed+add+framework).

I think `ServiceManagement` might be a bit troublesome though, since it parts of it relies on `CoreFoundation`, which we don't yet map. But maybe you can get away with just adding those as `skipped = true` to `translation-config.toml`?

**Comment by dongcarl** [comment]
> The easiest instruction for me to give would be to look at [other PRs adding frameworks](https://github.com/madsmtm/objc2/pulls?q=is%3Apr+is%3Aclosed+add+framework).

Makes sense.

> I think `ServiceManagement` might be a bit troublesome though, since it parts of it relies on `CoreFoundation`, which we don't yet map.

I'm guessing the references to `CF*` classes are the parts that rely on `CoreFoundation` right? I really just care about `SMAppService`, which doesn't seem to rely on `CF*` classes and only `NSString`, `NSError`, and an `NSInteger` enum.

**Comment by madsmtm** [comment]
> I'm guessing the references to `CF*` classes are the parts that rely on `CoreFoundation` right?

Yup

**Comment by dongcarl** [comment]
I'm looking at #506 and updating all the files just like how it's done there. But `cargo build` doesn't seem to generate new files in `crates/icrate/src/generated`, so I must be missing something. Wondering what best to do?

**Comment by julian-baumann** [comment]
Running ` cargo run --bin header-translator` on a freshly cloned repo exits with this error:
```
thread 'main' panicked at crates/header-translator/src/rust_type.rs:1002:18:
unsupported type: Type { kind: ObjCObject, display_name: "NSDictionary<NSString *,id>" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
│ ├─┘
├─┘
```

I haven't modified anything yet, since I just wanted to test whether it works or not. Am I doing something wrong? I cloned this repo and initialized the submodules with `git submodule update --init`. Is there something I am missing?

**Comment by madsmtm** [comment]
Again, what version of Xcode and Clang are you using?

**Comment by julian-baumann** [comment]
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Xcode: Version 15.1

**Comment by madsmtm** [comment]
Perhaps try with Xcode 15.0.1 (or just the SDKs from there)? I haven't gotten around to updating `icrate` to Xcode 15.1 yet.

**Comment by madsmtm** [comment]
I've fixed the issues you were having @julian-baumann in https://github.com/madsmtm/objc2/pull/548, and have updated to Xcode 15.1 in the meantime.
