### ISSUE TITLE
Swift array count: expected return to have type code 'q', but found 'Q'

### ISSUE THREAD

**Issue by 1tgr** [madsmtm/objc2#566]
I'm exposing this Rust function to Swift:

```rust
#[no_mangle]
pub extern "C" fn time_series_eval(
    exprs: *mut NSArray<NSString>,
    error: &mut *mut NSError,
) -> *mut NSDictionary<NSString, NSArray> {
    let exprs = exprs.as_ref().unwrap().iter();
    // do something with exprs
}
```

I call it like this from the Swift side:
```swift
var error: NSError?
let result = time_series_eval(["abc"], &error)
```

But the Rust panics:
```
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/icrate-0.1.0/src/generated/Foundation/NSEnumerator.rs:6:1:
invalid message send to -[Swift.__SwiftDeferredNSArray countByEnumeratingWithState:objects:count:]: expected return to have type code 'q', but found 'Q'
```

I think this is telling me that Swift arrays and objc2's arrays don't agree on signed vs unsigned?

**Comment by madsmtm** [comment]
> I think this is telling me that Swift arrays and objc2's arrays don't agree on signed vs unsigned?

Rather, Swift is lazy and uses `Int` instead of the more correct type `UInt` here; the difference doesn't really matter to them, as arrays likely won't be able to ever get that large.

I've opened https://github.com/madsmtm/objc2/pull/567 to fix this, although I'm a bit unsure what the right approach is. In the meantime the easiest fix for you is probably to do one of:
- Patch in https://github.com/madsmtm/objc2/pull/567 locally (using the `patch.crates-io` Cargo.toml key).
- Re-implement the iteration yourself using `objectAtIndex:`.
- Disable debug assertions.

**Comment by madsmtm** [comment]
I went with a Cargo feature flag called `relax-sign-encoding`, you should be able to use that instead once I release `objc2 v0.5.2`

**Comment by madsmtm** [comment]
Would it be possible for you to give me a code example that miscompiles if I use `-> u8` in the signature instead of `-> i8` (or vice-versa)?

And similarly for `-> usize` and `-> isize`?

**Comment by madsmtm** [comment]
Hmm, I can reproduce your result, but from my testing, it doesn't seem to produce differing results if I do `int8_t foo();`? So maybe what we're seeing here is more a problem with C's implicit integer casting rules?

In any case, the thing I'm really interested in is whether you know a case where zero/sign extension happens when taking/returning register-sized types?

**Comment by madsmtm** [comment]
Thanks for the clarification!
