### ISSUE TITLE
`currentDrawable` property is not accessible in `MTKView` 

### ISSUE THREAD

**Issue by dmbfm** [madsmtm/objc2#570]
When using `MTKView` for rendering with the Metal API there seems to be no way to access the [`currentDrawable`](https://developer.apple.com/documentation/metalkit/mtkview/currentdrawable?language=objc) property of `MTKView` so we can present it. 

Currently I do this as a workaround and it works fine:

```rust

type ID<T> = Id<ProtocolObject<T>>;

trait MTKViewCurrentDrawable {
    fn current_drawable(&self) -> Option<ID<dyn MTLDrawable>>;
}

impl MTKViewCurrentDrawable for MTKView {
    fn current_drawable(&self) -> Option<ID<dyn MTLDrawable>> {
        unsafe { msg_send_id![self, currentDrawable] }
    }
}
```

**Comment by madsmtm** [comment]
That's because it actually returns [`CAMetalDrawable`](https://developer.apple.com/documentation/quartzcore/cametaldrawable/1478165-layer?language=objc), which itself is kinda weird; it exists in the `QuartzCore`/`CoreAnimation` framework (along with a bunch of other `CAMetalX`), but extends the `MTLDrawable` protocol from the `Metal` framework, so there's a kind of circular dependency here, which I think I was unsure of how to resolve cleanly.

**Comment by madsmtm** [comment]
I've fixed part of this in https://github.com/madsmtm/objc2/commit/0f1479ba6f9fe368f1bf0c872d3fe8cff46c4337, the `QuartzCore` framework wasn't properly public, so we couldn't really use it in the other frameworks.

Still need to actually generate the `CAMetalDrawable` class.
