### ISSUE TITLE
The feature flag for the number module in objc2-foundation appears to be incorrect

### ISSUE THREAD

**Issue by libark** [madsmtm/objc2#607]
```diff --git a/framework-crates/objc2-foundation/src/lib.rs b/framework-crates/objc2-foundation/src/lib.rs
index e4d76533..372c0b3d 100644
--- a/framework-crates/objc2-foundation/src/lib.rs
+++ b/framework-crates/objc2-foundation/src/lib.rs
@@ -110,7 +110,7 @@ mod generics;
 mod geometry;
 mod macros;
 mod ns_consumed;
-#[cfg(feature = "NSValue")]
+#[cfg(feature = "NSNumber")]
 mod number;
 #[cfg(feature = "NSProcessInfo")]
 mod process_info;```

**Comment by madsmtm** [comment]
It isn't, `NSNumber` is defined in `Foundation/NSValue.h`, so that's the feature flag that it should use. See [this link](https://docs.rs/objc2/0.5.1/objc2/topics/about_generated/cargo_features/index.html) for information about cargo features in framework crates.

The `number` module is just a few extension methods that we've implemented manually, they could've been placed anywhere.
