### ISSUE TITLE
No `AXUIElement`

### ISSUE THREAD

**Issue by AurevoirXavier** [madsmtm/objc2#624]
First, I apologize for opening a question here.

Can I use this crate to get the currently selected text?

I did find `fn accessibilityFocusedUIElement(&self, ..)` and `objc2_app_kit::NSAccessibilityFocusedUIElementAttribute`. But I couldn't find `AXUIElement`. So, how to obtain the `&self` `NSObjectNSAccessibility`? Then I can call `accessibilityFocusedUIElement` on it.

**Comment by madsmtm** [comment]
> First, I apologize for opening a question here.

No problem, please do!

> No `AXUIElement`

`AXUIElement` comes from the ApplicationServices framework, which is why it is not defined just by importing AppKit.

That framework in particular is "CoreFoundation-like", and is not yet supported, see https://github.com/madsmtm/objc2/issues/556.

> Can I use this crate to get the currently selected text?

Hmm, I'm not too familiar with the accessibility frameworks, but if you have e.g. a NSView, I believe you can just import `NSObjectNSAccessibility`, and then you should be able to call `accessibilityFocusedUIElement`?

In any case, I can recommend [the AccessKit project](https://github.com/AccessKit/accesskit), they abstract a lot of this for you, and their source code probably contain similar things as what you're trying to do.

**Comment by AurevoirXavier** [comment]
> Hmm, I'm not too familiar with the accessibility frameworks, but if you have e.g. a NSView, I believe you can just import NSObjectNSAccessibility, and then you should be able to call accessibilityFocusedUIElement?

I'll get `fatal runtime error: Rust cannot catch foreign exceptions` if I call `accessibilityFocusedUIElement`.

> In any case, I can recommend [the AccessKit project](https://github.com/AccessKit/accesskit), they abstract a lot of this for you, and their source code probably contain similar things as what you're trying to do.

Thanks, I'll take a look!

**Comment by madsmtm** [comment]
> I'll get `fatal runtime error: Rust cannot catch foreign exceptions`

Try running with `objc2`'s `catch-all` feature - then you will see that the exception is:
```
uncaught exception <NSException: 0x128811df0> 'NSInvalidArgumentException' reason:-[NSRunningApplication accessibilityFocusedUIElement]: unrecognized selector sent to instance 0x128810c00
```

(If debug assertions are enabled, then `objc2` should also have picked it up as `invalid message send to -[NSRunningApplication accessibilityFocusedUIElement]: method not found`).

I'm not sure, but I'm beginning to suspect that `accessibilityFocusedUIElement` is perhaps something meant for you to _override_, not call?

**Comment by AurevoirXavier** [comment]
I finally resolved it using https://github.com/eiz/accessibility. Thanks.
