### ISSUE TITLE
Use extern_class macro with classes declared in swift via @objc

### ISSUE THREAD

**Issue by lucasmerlin** [madsmtm/objc2#642]
Is it possible to use the extern_class macro with classes declared in swift via @objc? 

I have the following swift class: 
```swift
@objc public class GlobalFunctions: NSObject {
    @objc public static func objcDummyFn(data: NSString) {
        showAlert(text: data as String)
    }
}
```

and the following rust code: 

```rust
extern_class!(
  #[derive(Debug)]
  pub struct GlobalFunctions;

  unsafe impl ClassType for GlobalFunctions {
    type Super = NSObject;
    type Mutability = mutability::InteriorMutable;
  }
);


extern_methods!(
  unsafe impl GlobalFunctions {
    #[method(objcDummyFnWithData:)]
    pub fn objcDummyFn(data: &NSString);
  }
);
```

When I try calling `GlobalFunctions::objcDummyFn`, I get `class GlobalFunctions could not be found`. Do I need to do anything else or is this just not supported? If I declare the class with Objective C instead of Swift it works as expected.

**Comment by madsmtm** [comment]
The generated Objective-C bridging header contains something like:
```objc
SWIFT_CLASS("_TtC14objc2_issue64215GlobalFunctions")
@interface GlobalFunctions : NSObject
+ (void)objcDummyFnWithData:(NSString * _Nonnull)data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end
```

That is, because Swift is name-mangling `GlobalFunctions`, it still tells the C compiler what the actual name of the class is (in my case `_TtC14objc2_issue64215GlobalFunctions`, which is the mangled name of `objc2_issue642.GlobalFunctions`, which is what I called my project).

To solve this, you'd either tell the Rust code the name too:
```rust
extern_class!(
  #[derive(Debug)]
  pub struct GlobalFunctions;

  unsafe impl ClassType for GlobalFunctions {
    type Super = NSObject;
    type Mutability = mutability::InteriorMutable;
    // NOTE: We specify the mangled name here explicitly
    const NAME: &'static str = "_TtC14objc2_issue64215GlobalFunctions";
  }
);
```

Or you'd tell Swift to not mangle the class name:
```swift
// We specify the desired name inside `@objc(...)`
@objc(GlobalFunctions) public class GlobalFunctions: NSObject {
    // ...
}
```

I'm pretty sure that's the answer, so I'm going to close this, but feel free to reopen and ask further questions!

**Comment by lucasmerlin** [comment]
This is awesome! I was able to remove all my Objective-C glue code. Also the trick of looking at the generated swift bridging header is really helpful to figure out the right method names. Thank you!
