### ISSUE TITLE
Question: why to cache the selectors?

### ISSUE THREAD

**Issue by Berrysoft** [madsmtm/objc2#666]
I've found that the selectors in `objc2` are cached after first call to `sel_registerName`. However, it seems that clang doesn't do the same thing, and there is a cache system inside `sel_registerName`. Why do we cache it a second time?

The way to check how clang compiles:
```objc
// test.m
#import <Foundation/Foundation.h>
int main() {
    NSObject *obj = [NSObject performSelector:@selector(sel)];
}
```
Call `clang -rewrite-objc test.m -O3`, and check the tail of file `test.cpp`:
```cpp
// ... many preprocessing code
int main() {
 NSObject *obj = ((id (*)(id, SEL, SEL))(void *)objc_msgSend)((id)objc_getClass("NSObject"), sel_registerName("performSelector:"), sel_registerName("sel"));
}
// ... others
```

It seems that class object and selector object are not cached by clang.

**Comment by madsmtm** [comment]
> I've found that the selectors in `objc2` are cached after first call to `sel_registerName`. [...] there is a cache system inside `sel_registerName`. Why do we cache it a second time?

Short answer: Performance.

The "cache" inside `sel_registerName` isn't really a cache in that sense, it's [interning](https://en.wikipedia.org/wiki/Interning_(computer_science)) the selectors so that comparisons between selectors is fast (i.e. it can be a pointer comparison instead of having to compare each byte in the selector). And interning takes a fair bit of time, which is why we cache it externally.

Does that make sense?

> it seems that clang doesn't do the same thing

I think you may be mistaken here; I can't remember exactly which flags are required, but try compiling with some combination of `-ObjC`, `-target aarch64-apple-macosx` or `-fobjc-runtime=...`, then you should see Clang using specially named statics that are resolved by `dyld` before the program starts (i.e. the ultimate form of selector caching).

`objc2` actually has support for this mode as well, it's behind the `"unstable-static-sel"` feature flag (but is unstable because it has issues with current `rustc` when the statics are split into different codegen units).

**Comment by Berrysoft** [comment]
Thank you very much! I'll look into these feature flags.
